version: "3.4"
  
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    network_mode: host
    environment:
      NODE_ENV: dev
      DB_PASSWORD: pwd1234
    user: node
    volumes:
      - ./:/src
  db-dev:
    image: postgres:11
    network_mode: host
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pwd1234
  
